homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Main:index }

about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Main:aboutMe }

guestbook:
    pattern:  /guestbook
    defaults: { _controller: BlogBundle:Main:guest }

article:
    pattern:  /article/{id}
    defaults: { _controller: BlogBundle:Main:article }

more_articles:
    pattern: /morearticles
    defaults: { _controller: BlogBundle:Main:moreArticle }

more_posts:
    pattern: /moreposts
    defaults: { _controller: BlogBundle:Main:morePosts }

add_article:
    pattern: /admin/addarticle
    defaults: { _controller: BlogBundle:Backend:addArticle }

del_post:
    pattern: /admin/delpost
    defaults: { _controller: BlogBundle:Backend:delPost }