homepage:
    pattern:  /
    defaults: { _controller: BlogBundle:Main:index }

about:
    pattern:  /about
    defaults: { _controller: BlogBundle:Main:about }

guestbook:
    pattern:  /guestbook
    defaults: { _controller: BlogBundle:Main:guest }

article:
    pattern:  /article/{id}
    defaults: { _controller: BlogBundle:Main:article }