fos_user_security_login:
    pattern: /login
    defaults: { _controller: BlogBundle:Backend:login }

fos_user_security_check:
    pattern: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

fos_user_security_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }