homepage:
    pattern:  /
    defaults: { _controller: AcmeWork6Bundle:Main:index }

planes:
    pattern:  /planes
    defaults: { _controller: AcmeWork6Bundle:Main:planes }

engines:
    pattern:  /engines
    defaults: { _controller: AcmeWork6Bundle:Main:engines }

weapons:
    pattern:  /weapons
    defaults: { _controller: AcmeWork6Bundle:Main:weapons }

plane:
    pattern:  /plane/{id}
    defaults: { _controller: AcmeWork6Bundle:Main:plane }

engine:
    pattern:  /engine/{id}
    defaults: { _controller: AcmeWork6Bundle:Main:engine }

weapon:
    pattern:  /weapon/{id}
    defaults: { _controller: AcmeWork6Bundle:Main:weapon }

contact:
    pattern:  /contact
    defaults: { _controller: AcmeWork6Bundle:Main:contact }

mail:
    pattern:  /sendmail
    defaults: { _controller: AcmeWork6Bundle:Main:mail }

guest:
    pattern:  /guest
    defaults: { _controller: AcmeWork6Bundle:Main:guest }