parameters:
    ViewPlanes.class:      Acme\Work6Bundle\Services\ViewPlanes
    MyMailer.class:        Acme\Work6Bundle\Services\MyMailer

services:
    ViewPlanes:
        class:      "%ViewPlanes.class%"
        arguments:  ["@doctrine"]
    MyMailer:
        class:      "%MyMailer.class%"
        arguments:  ["@mailer"]